"use client";

import type { AssistantResponse } from "@/lib/db/types";
import { RiskBadge } from "@/components/ui/RiskBadge";
import { speakText } from "./VoiceRecorder";
import type { ReactNode } from "react";

interface Props {
  response: AssistantResponse;
  uiLang: "es" | "en";
  actions?: ReactNode;
}

// Nombres para mostrar de cada valor posible de selectedProvider/
// attemptedProvider/actualProvider (ver lib/db/types.ts#AssistantResponse).
// CRITICO: "gemini"/"openai" en actualProvider SOLO deben mostrarse cuando
// ese proveedor realmente produjo el texto. Si fallo, actualProvider ya
// viene como "local_validated_fallback" desde app/api/queries/route.ts, asi
// que este mapa nunca muestra "Gemini" como autor de una respuesta que
// Gemini no genero.
const PROVIDER_DISPLAY_NAME = {
  es: {
    gemini: "Gemini",
    openai: "OpenAI",
    mock: "Motor local",
    none: "Ninguno",
    local_validated_fallback: "Motor tecnico local",
    supabase_knowledge_entries: "Base de conocimiento (Supabase)"
  },
  en: {
    gemini: "Gemini",
    openai: "OpenAI",
    mock: "Local engine",
    none: "None",
    local_validated_fallback: "Local technical engine",
    supabase_knowledge_entries: "Knowledge base (Supabase)"
  }
} as const;

const LABELS = {
  es: {
    shortAnswer: "1. Respuesta corta",
    englishSummary: "English summary",
    explanation: "Explicacion",
    codeReference: "2. NEC aplicable / regulacion aplicable",
    officialSourceNote: "3. Fuente oficial consultada o recomendada",
    practicalApplication: "4. Aplicacion practica",
    doNotAssume: "5. Cuando no asumir",
    planReading: "Lectura del plano",
    checklist: "6. Checklist de campo",
    commonMistakes: "Errores comunes",
    missingQuestions: "Preguntas faltantes",
    riskLevel: "7. Riesgo",
    recommendation: "Recomendacion adicional",
    finalVerification: "8. Verificacion final",
    warning: "Advertencia",
    sourceInfo: "Base interna usada para esta respuesta",
    listen: "Escuchar",
    sheet: "Hoja",
    symbols: "Simbolos visibles",
    equipment: "Equipos identificados",
    panels: "Paneles identificados",
    circuits: "Circuitos visibles",
    notes: "Notas relevantes",
    missingInfo: "Informacion faltante",
    metaSelectedProvider: "Proveedor seleccionado",
    metaActualProvider: "Respuesta generada por",
    metaAnswerKind: "Estado",
    metaAttemptedModel: "Modelo intentado",
    metaFallbackReason: "Motivo del fallback",
    metaSource: "Fuente interna",
    answerKindBacked: "Respaldada",
    answerKindValidatedFallback: "Fallback validado",
    answerKindUnverified: "Sin verificar"
  },
  en: {
    shortAnswer: "1. Short answer",
    englishSummary: "English summary",
    explanation: "Explanation",
    codeReference: "2. Applicable NEC / applicable regulation",
    officialSourceNote: "3. Official source consulted or recommended",
    practicalApplication: "4. Practical application",
    doNotAssume: "5. When not to assume",
    planReading: "Plan reading",
    checklist: "6. Field checklist",
    commonMistakes: "Common mistakes",
    missingQuestions: "Missing questions",
    riskLevel: "7. Risk",
    recommendation: "Additional recommendation",
    finalVerification: "8. Final verification",
    warning: "Warning",
    sourceInfo: "Internal base used for this response",
    listen: "Listen",
    sheet: "Sheet",
    symbols: "Visible symbols",
    equipment: "Identified equipment",
    panels: "Identified panels",
    circuits: "Visible circuits",
    notes: "Relevant notes",
    missingInfo: "Missing information",
    metaSelectedProvider: "Selected provider",
    metaActualProvider: "Response generated by",
    metaAnswerKind: "Status",
    metaAttemptedModel: "Model attempted",
    metaFallbackReason: "Fallback reason",
    metaSource: "Internal source",
    answerKindBacked: "Backed",
    answerKindValidatedFallback: "Validated fallback",
    answerKindUnverified: "Unverified"
  }
} as const;

const ANSWER_KIND_STYLES: Record<string, string> = {
  backed: "border-green-600/50 bg-green-600/10 text-green-400",
  validated_fallback: "border-fly-gold/50 bg-fly-gold/10 text-fly-gold",
  unverified: "border-risk-critical/50 bg-risk-critical/10 text-risk-critical"
};

const ANSWER_KIND_LABEL_KEY: Record<string, keyof (typeof LABELS)["es"]> = {
  backed: "answerKindBacked",
  validated_fallback: "answerKindValidatedFallback",
  unverified: "answerKindUnverified"
};

function providerName(uiLang: "es" | "en", value: string | undefined | null): string | null {
  if (!value) return null;
  const names = PROVIDER_DISPLAY_NAME[uiLang] as Record<string, string>;
  return names[value] ?? value;
}

export function AssistantResponseCard({ response, uiLang, actions }: Props) {
  const L = LABELS[uiLang];
  const hasMetadata = Boolean(response.selectedProvider || response.actualProvider || response.answerKind || response.internalSourceUsed);
  // "Modelo intentado" solo tiene sentido cuando SI se llamo a un proveedor
  // real (gemini/openai); si el proveedor elegido fue el motor local desde
  // el inicio, no hubo ningun "intento" de modelo que reportar.
  const attemptedModel =
    response.attemptedProvider === "gemini" || response.attemptedProvider === "openai" ? response.providerModel : null;

  return (
    <div className="rounded-2xl border border-fly-gray bg-fly-charcoal p-5 space-y-4">
      {/* Item 3 del pedido: trazabilidad de proveedor SIEMPRE visible y
          SIEMPRE separando "quien esta configurado" de "quien realmente
          genero este texto" (actualProvider). Nunca muestra "Gemini" como
          autor si Gemini fallo: en ese caso actualProvider ya llega como
          "local_validated_fallback" desde app/api/queries/route.ts. */}
      {hasMetadata && (
        <dl className="grid grid-cols-[max-content_1fr] gap-x-3 gap-y-1 text-xs border border-fly-gray/60 rounded-xl p-3">
          {response.selectedProvider && (
            <>
              <dt className="text-fly-lightgray/60">{L.metaSelectedProvider}:</dt>
              <dd>{providerName(uiLang, response.selectedProvider)}</dd>
            </>
          )}
          {response.actualProvider && (
            <>
              <dt className="text-fly-lightgray/60">{L.metaActualProvider}:</dt>
              <dd className="font-medium">{providerName(uiLang, response.actualProvider)}</dd>
            </>
          )}
          {response.answerKind && (
            <>
              <dt className="text-fly-lightgray/60">{L.metaAnswerKind}:</dt>
              <dd>
                <span className={`rounded-full border px-2 py-0.5 font-medium ${ANSWER_KIND_STYLES[response.answerKind] ?? "border-fly-gray/60 text-fly-lightgray/80"}`}>
                  {L[ANSWER_KIND_LABEL_KEY[response.answerKind]] ?? response.answerKind}
                </span>
              </dd>
            </>
          )}
          {attemptedModel && (
            <>
              <dt className="text-fly-lightgray/60">{L.metaAttemptedModel}:</dt>
              <dd>{attemptedModel}</dd>
            </>
          )}
          {response.providerFallback && response.providerErrorCode && (
            <>
              <dt className="text-fly-lightgray/60">{L.metaFallbackReason}:</dt>
              <dd className="text-fly-lightgray/80">{response.providerErrorCode}</dd>
            </>
          )}
          {response.internalSourceUsed && (
            <>
              <dt className="text-fly-lightgray/60">{L.metaSource}:</dt>
              <dd className="text-fly-lightgray/80 break-words">{response.internalSourceUsed}</dd>
            </>
          )}
        </dl>
      )}

      <section>
        <div className="flex items-center justify-between gap-2 mb-1">
          <h3 className="text-fly-gold font-bold text-sm uppercase tracking-wide">{L.shortAnswer}</h3>
          <button
            type="button"
            onClick={() => speakText(response.shortAnswer, uiLang === "en" ? "en-US" : "es-US")}
            className="text-xs text-fly-lightgray/70 hover:text-fly-gold underline"
          >
            🔊 {L.listen}
          </button>
        </div>
        <p className="text-base leading-relaxed whitespace-pre-line">{response.shortAnswer}</p>
      </section>

      {response.englishSummary && (
        <section>
          <h3 className="text-fly-gold font-bold text-sm uppercase tracking-wide mb-1">{L.englishSummary}</h3>
          <p className="text-base leading-relaxed text-fly-lightgray">{response.englishSummary}</p>
        </section>
      )}

      {/* Sprint 2: campo opcional, separado de shortAnswer. Ausente en las
          21 entradas anteriores a Sprint 2 y en respuestas de proveedores de
          IA -> no se renderiza ninguna seccion vacia en esos casos. */}
      {response.explanation && (
        <section>
          <h3 className="text-fly-gold font-bold text-sm uppercase tracking-wide mb-1">{L.explanation}</h3>
          <p className="text-sm text-fly-lightgray whitespace-pre-line">{response.explanation}</p>
        </section>
      )}

      <section>
        <h3 className="text-fly-gold font-bold text-sm uppercase tracking-wide mb-1">{L.codeReference}</h3>
        <p className="text-sm text-fly-lightgray whitespace-pre-line">{response.codeReference}</p>
      </section>

      {response.officialSourceNote && (
        <section className="border border-fly-gray/60 rounded-xl p-3">
          <h3 className="text-fly-gold font-bold text-sm uppercase tracking-wide mb-1">{L.officialSourceNote}</h3>
          <p className="text-xs text-fly-lightgray whitespace-pre-line">{response.officialSourceNote}</p>
        </section>
      )}

      {response.practicalApplication && (
        <section>
          <h3 className="text-fly-gold font-bold text-sm uppercase tracking-wide mb-1">{L.practicalApplication}</h3>
          <p className="text-sm">{response.practicalApplication}</p>
        </section>
      )}

      {response.doNotAssume && (
        <section>
          <h3 className="text-fly-gold font-bold text-sm uppercase tracking-wide mb-1">{L.doNotAssume}</h3>
          <p className="text-sm text-fly-lightgray whitespace-pre-line">{response.doNotAssume}</p>
        </section>
      )}

      {response.planReading && (
        <section className="border border-fly-gray/60 rounded-xl p-3 space-y-1">
          <h3 className="text-fly-gold font-bold text-sm uppercase tracking-wide mb-1">{L.planReading}</h3>
          {response.planReading.sheet && (
            <p className="text-sm">
              <span className="text-fly-lightgray/70">{L.sheet}: </span>
              {response.planReading.sheet}
            </p>
          )}
          <PlanReadingList label={L.symbols} items={response.planReading.symbolsVisible} />
          <PlanReadingList label={L.equipment} items={response.planReading.equipmentIdentified} />
          <PlanReadingList label={L.panels} items={response.planReading.panelsIdentified} />
          <PlanReadingList label={L.circuits} items={response.planReading.circuitsVisible} />
          <PlanReadingList label={L.notes} items={response.planReading.notes} />
          <PlanReadingList label={L.missingInfo} items={response.planReading.missingInfo} />
        </section>
      )}

      <section>
        <h3 className="text-fly-gold font-bold text-sm uppercase tracking-wide mb-1">{L.checklist}</h3>
        <ul className="space-y-1">
          {response.checklist.map((item, idx) => (
            <li key={idx} className="flex gap-2 text-sm">
              <input type="checkbox" className="mt-1" />
              <span>{item}</span>
            </li>
          ))}
        </ul>
      </section>

      {/* Sprint 2: lista separada del checklist (nunca fusionada dentro de
          el). Ausente en las 21 entradas anteriores a Sprint 2 -> no se
          renderiza ninguna seccion vacia en esos casos. */}
      {response.commonMistakes && response.commonMistakes.length > 0 && (
        <section>
          <h3 className="text-fly-gold font-bold text-sm uppercase tracking-wide mb-1">{L.commonMistakes}</h3>
          <ul className="list-disc list-inside text-sm space-y-1 text-fly-lightgray">
            {response.commonMistakes.map((item, idx) => (
              <li key={idx}>{item}</li>
            ))}
          </ul>
        </section>
      )}

      {response.missingQuestions.length > 0 && (
        <section>
          <h3 className="text-fly-gold font-bold text-sm uppercase tracking-wide mb-1">{L.missingQuestions}</h3>
          <ul className="list-disc list-inside text-sm space-y-1 text-fly-lightgray">
            {response.missingQuestions.map((q, idx) => (
              <li key={idx}>{q}</li>
            ))}
          </ul>
        </section>
      )}

      <section className="flex items-center gap-3">
        <h3 className="text-fly-gold font-bold text-sm uppercase tracking-wide">{L.riskLevel}</h3>
        <RiskBadge risk={response.riskLevel} lang={uiLang} />
      </section>

      <section>
        <h3 className="text-fly-gold font-bold text-sm uppercase tracking-wide mb-1">{L.recommendation}</h3>
        <p className="text-sm">{response.recommendation}</p>
      </section>

      {response.finalVerification && (
        <section className="bg-fly-black/60 border border-fly-gold/50 rounded-xl p-3">
          <h3 className="text-fly-gold font-bold text-sm uppercase tracking-wide mb-1">{L.finalVerification}</h3>
          <p className="text-xs text-fly-lightgray whitespace-pre-line">{response.finalVerification}</p>
        </section>
      )}

      <section className="bg-fly-black/60 border border-fly-gold/50 rounded-xl p-3">
        <h3 className="text-fly-gold font-bold text-sm uppercase tracking-wide mb-1">{L.warning}</h3>
        <p className="text-xs text-fly-lightgray whitespace-pre-line">{response.warning}</p>
      </section>

      {response.sourceInfo && (
        <section className="border border-fly-gray/60 rounded-xl p-3">
          <h3 className="text-fly-gold font-bold text-sm uppercase tracking-wide mb-1">{L.sourceInfo}</h3>
          <p className="text-xs text-fly-lightgray whitespace-pre-line">{response.sourceInfo}</p>
        </section>
      )}

      {actions && <div className="flex flex-col gap-2 pt-2">{actions}</div>}
    </div>
  );
}

function PlanReadingList({ label, items }: { label: string; items: string[] }) {
  if (items.length === 0) return null;
  return (
    <p className="text-sm">
      <span className="text-fly-lightgray/70">{label}: </span>
      {items.join(", ")}
    </p>
  );
}
